# Default values for demo_microservices.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

postgres:
  enabled: true
  name: postgres
  image:
    repository: postgres
    tag: 12.1
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5432
  persistentVolume:
    storageClass: microk8s-hostpath
    size: 20Mi

debezium:
  enabled: true
  name: debezium-connect
  image:
    repository: debezium/connect
    tag: 1.1
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8083

kafkaConnect:
  enabled: disabled
  name: kafka-connect
  image:
    repository: confluentinc/cp-kafka-connect
    tag: 5.4.0
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8083

