version: '3.7'
services:
  flask:
    image: webapp-flask
    build:
      context: ./flask
      dockerfile: Dockerfile-flask
    environment: 
    - MY_ENV_VAR="hello beautiful environment!"

  nginx:
    image: webapp-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:8082
    depends_on:
      - flask

