apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apmServer.name }}
  labels:
    app: {{ .Values.apmServer.name }}
    {{- include "oht-devops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apmServer.service.type }}
  ports:
    - port: {{ .Values.apmServer.service.port }}
      targetPort: http
      nodePort: {{ .Values.apmServer.service.nodePort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.apmServer.name }}
    {{- include "oht-devops.selectorLabels" . | nindent 4 }} 
