apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apmServer.name }}
  labels:
    app: {{ .Values.apmServer.name }}
    {{- include "oht-devops.labels" . | nindent 4 }}
spec:
{{ if eq .Values.environment "local" }}
  type: {{ .Values.apmServer.service.local.type }}
  ports:
    - port: {{ .Values.apmServer.service.local.port }}
      targetPort: http
      nodePort: {{ .Values.apmServer.service.local.nodePort }}
      protocol: TCP
      name: http
{{ else if eq .Values.environment "azure" }}
  type: {{ .Values.apmServer.service.azure.type }}
  ports:
    - port: {{ .Values.apmServer.service.azure.port }}
      targetPort: http
      protocol: TCP
      name: http
{{ end }}
  selector:
    app: {{ .Values.apmServer.name }}
    {{- include "oht-devops.selectorLabels" . | nindent 4 }} 
