{{ if eq .Values.environment "sandbox" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "oht-devops.labels" . | nindent 4 }}
  name: {{ .Values.elasticsearch.name }}-pv
spec:
  accessModes:
  - ReadWriteMany
{{ if eq .Values.environment "local" }}
  storageClassName: "{{ .Values.elasticsearch.persistentVolume.local.storageClass }}"
  resources:
    requests:
      storage: "{{ .Values.elasticsearch.persistentVolume.local.size }}"
{{ else if eq .Values.environment "azure" }}
  storageClassName: "{{ .Values.elasticsearch.persistentVolume.azure.storageClass }}"
  resources:
    requests:
      storage: "{{ .Values.elasticsearch.persistentVolume.azure.size }}"
{{ end }}

{{ end }}
