apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "oht-devops.labels" . | nindent 4 }}
  name: {{ .Values.elasticsearch.name }}-pv
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: "{{ .Values.elasticsearch.persistentVolume.storageClass }}"
  resources:
    requests:
      storage: "{{ .Values.elasticsearch.persistentVolume.size }}"

