apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fluentd.name }}
  labels:
    app: {{ .Values.fluentd.name }}
    {{- include "oht-devops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.fluentd.service.type }}
  ports:
    - port: 9880
      targetPort: http
      protocol: TCP
      name: http
    - port: 24224
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app: {{ .Values.fluentd.name }}
    {{- include "oht-devops.selectorLabels" . | nindent 4 }} 
