apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.kibana.name }}
  labels:
    app: {{ .Values.kibana.name }}
    {{- include "oht-devops.labels" . | nindent 4 }}
spec:
  type: {{ .Values.kibana.service.type }}
  ports:
    - port: {{ .Values.kibana.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.kibana.name }}
    {{- include "oht-devops.selectorLabels" . | nindent 4 }} 
