apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "oht-devops.labels" . | nindent 4 }}
  name: {{ .Values.kibana.name }}-pv
spec:
  accessModes:
  - ReadWriteOnce
{{ if eq .Values.environment "local" }}
  storageClassName: "{{ .Values.kibana.persistentVolume.local.storageClass }}"
  resources:
    requests:
      storage: "{{ .Values.kibana.persistentVolume.local.size }}"
{{ else }}
  storageClassName: "{{ .Values.kibana.persistentVolume.azure.storageClass }}"
  resources:
    requests:
      storage: "{{ .Values.kibana.persistentVolume.azure.size }}"
{{ end }}
