apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceAccounts.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceAccounts.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccounts.name }}




