kind: DeploymentConfig # Kind is a string value representing the REST resource this object represents.
apiVersion: v1 # APIVersion defines the versioned schema of this representation of an object.
metadata: # Standard object metadata
  labels: # Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. 
    app: flask-app
  name: flask-app # Name must be unique within a namespace, primarily intended for creation idempotence and configuration definition.
  namespace: myproject # Namespace/Project for where the resource is.
spec: # Spec represents a desired deployment state and how to deploy to it.
  template: # Template is the object that describes the pod that will be created if insufficient replicas are detected.
    metadata: # Standard object metadata
      labels: # Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services
        app: flask-app
        deploymentconfig: flask-app
    spec: # Specification of the desired behavior of the pod.
      containers: # List of containers belonging to the pod. Containers cannot currently be added or removed. There must be at least one container in a Pod. 
        - name: flask-app # Name of the container
          image: 172.30.1.1:5000/myproject/flask-app # Docker image name
          ports: # List of ports to expose from the container. Exposing a port here gives the system additional information about the network connections a container uses, but is primarily informational. 
            - containerPort: 5000
              protocol: "TCP"
          livenessProbe: # Periodic probe of container liveness. Container will be restarted if the probe fails. 
            failureThreshold: 3 # Minimum consecutive failures for the probe to be considered failed after having succeeded.
            httpGet: # HTTPGet specifies the http request to perform.
              path: / # Path to access on the HTTP server.
              port: 5000 # Name or number of the port to access on the container.
              scheme: HTTP # Scheme to use for connecting to the host.
            periodSeconds: 10 # How often (in seconds) to perform the probe.
            successThreshold: 1 # Minimum consecutive successes for the probe to be considered successful after having failed. 
            timeoutSeconds: 1 # Number of seconds after which the probe times out.
          readinessProbe: # Periodic probe of container service readiness. Container will be removed from service endpoints if the probe fails.
            failureThreshold: 3 # Minimum consecutive failures for the probe to be considered failed after having succeeded.
            httpGet: # HTTPGet specifies the http request to perform.
              path: / # Path to access on the HTTP server.
              port: 5000 # Name or number of the port to access on the container.
              scheme: HTTP # Scheme to use for connecting to the host.
            periodSeconds: 10 # How often (in seconds) to perform the probe.
            successThreshold: 1 # Minimum consecutive successes for the probe to be considered successful after having failed. 
            timeoutSeconds: 1 # Number of seconds after which the probe times out.
          resources: # Compute resources requied by this container
            limits: # Maximum amount of compute resources required
              cpu: 2
              memory: 100Mi
            requests: # Minimum amount of compute resources required
              cpu: 1
              memory: 50Mi
  replicas: 2 # Number of desired replicas.
  triggers: # Triggers determine how updates to a DeploymentConfig result in new deployments.
    - type: ConfigChange
    - type: ImageChange 
      imageChangeParams:
        automatic: true # Automatic means that the detection of a new tag value should result in an image update inside the pod template.
        containerNames: # ContainerNames is used to restrict tag updates to the specified set of container names in a pod.
          - flask-app
        from: # From is a reference to an image stream tag to watch for changes
          kind: ImageStreamTag
          name: flask-app:1.0.0


