# We simply inherit the Python 3 image. This image does
# not particularly care what OS runs underneath
FROM python:3

# Create the directory for where our application code will be
# and instruct Docker to work from that directory from now on
RUN mkdir /app
WORKDIR /app

# Expose the port uWSGI will listen on
EXPOSE 5000

# Copy the requirements file in order to install
# Python dependencies
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install -r requirements.txt

# We copy the rest of the codebase into the image
COPY app.py /app/

# We copy the uwsgi configuration file to a separate directory
COPY app.ini /etc/uwsgi/

# Finally, we run uWSGI with the ini file we created earlier
ENTRYPOINT [ "uwsgi", "--ini", "/etc/uwsgi/app.ini" ]

