apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-nginx
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: {{ .Values.kafkaConnect.name }}
          servicePort: {{ .Values.kafkaConnect.service.port }}
