apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.debezium.name }}
  labels:
    {{- include "demo_microservices.labels" . | nindent 4 }}
spec:
  type: {{ .Values.debezium.service.type }}
  ports:
    - port: {{ .Values.debezium.service.port }}
      targetPort: {{ .Values.debezium.service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.debezium.name }}
    {{- include "demo_microservices.selectorLabels" . | nindent 4 }}
