# Default values for demo_microservices.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

environment: azure
dns_prefix: cumulus

patient_ms:
  enabled: true
  name: patient-microservice
  image:
    repository: jchao100/patient-ms
    tag: latest
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 80
    targetPort: 4200

patient_ui:
  enabled: true
  name: patient-ui
  image:
    repository: jchao100/patient-ui
    tag: latest
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 80
    targetPort: 8080

postgres:
  enabled: true
  name: postgres
  image:
    repository: postgres
    tag: 12.1
    pullPolicy: Always
  service:
    type: NodePort
    port: 5432
    nodePort: 32650
  persistentVolume:
    local:
      storageClass: microk8s-hostpath
      size: 20Mi
    azure:
      storageClass: default
      size: 2Gi

mssql :
  enabled: false
  name: postgres
  image:
    repository: postgres
    tag: 12.1
    pullPolicy: Always
  service:
    type: NodePort
    port: 5432
    nodePort: 32650
  persistentVolume:
    local:
      storageClass: microk8s-hostpath
      size: 20Mi
    azure:
      storageClass: default
      size: 2Gi

debezium:
  enabled: true
  name: debezium-connect
  image:
    repository: debezium/connect
    tag: 1.1
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8083

kafkaConnect:
  enabled: false
  name: kafka-connect
  image:
    repository: confluentinc/cp-kafka-connect
    tag: 5.4.0
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 8083


observability:
  name: observability

