# Template values 

environment: azure

serviceAccounts:
  create: true
  name: kube-state-metrics

fluentd:
  enabled: true
  name: fluentd
  image:
    repository: localhost:32000/fluentd
    tag: v1.8.1-debian-1.0
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 24224
  persistentVolume:
    local:
      storageClass: microk8s-hostpath
      size: 20Mi
    azure:
      storageClass: default
      size: 5Gi

elasticsearch:
  enabled: true
  name: elasticsearch
  image:
    repository: elasticsearch
    tag: 7.6.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9200
  singleNode: true
  persistentVolume:
    local:
      storageClass: microk8s-hostpath
      size: 20Mi
    azure:
      storageClass: default
      size: 5Gi

apmServer:
  enabled: true
  name: apm-server
  image:
    repository: docker.elastic.co/apm/apm-server
    tag: 7.6.0
    pullPolicy: Always
  service:
    type: NodePort
    nodePort: 32655
    port: 8200

kibana:
  enabled: true
  name: kibana
  image:
    repository: kibana
    tag: 7.6.0
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5601
  persistentVolume:
    local:
      storageClass: microk8s-hostpath
      size: 20Mi
    azure:
      storageClass: default
      size: 5Gi

