# Template values 

environment: azure  # enum: local, azure
dns_prefix: cumulus

serviceAccounts:
  create: true
  name: efk

podSecurityContext:
  fsGroup: 1000

fluentd:
  enabled: true
  name: fluentd
  image:
    repository: jchao100/fluentd
    tag: v1.8.1-debian-1.0
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 24224
  resources:
    limits:
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 200Mi
  persistentVolume:
    local:
      storageClass: microk8s-hostpath
      size: 20Mi
    azure:
      storageClass: azurefile
      size: 5Gi

metricbeat:
  name: metricbeat
  image:
    repository: docker.elastic.co/beats/metricbeat
    tag: 7.6.1
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 0.5Gi

elasticsearch:
  roles:
    master: 3
    client: 3
    data: 3
  enabled: true
  podManagementPolicy: Parallel
  name: elasticsearch
  image:
    repository: elasticsearch
    tag: 7.6.1
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 9200
  resources:
    limits:
      cpu: 1000m
      memory: 3Gi
    requests:
      cpu: 100m
      memory: 3Gi
  persistentVolume:
    local:
      storageClass: microk8s-hostpath
      size: 20Mi
    azure:
      storageClass: default
      size: 5Gi

apmServer:
  enabled: true
  name: apm-server
  image:
    repository: docker.elastic.co/apm/apm-server
    tag: 7.6.1
    pullPolicy: Always
  service:
    local:
      type: NodePort
      nodePort: 32655
      port: 8200
    azure:
      type: LoadBalancer
      port: 80

kibana:
  enabled: true
  name: kibana
  image:
    repository: kibana
    tag: 7.6.1
    pullPolicy: IfNotPresent
  service:
    local:
      type: ClusterIP
      port: 5601
    azure:
      type: LoadBalancer
      port: 443
  resources:
    # need more cpu upon initialization, therefore burstable class
    limits:
      cpu: 1000m
    requests:
      cpu: 100m
  persistentVolume:
    local:
      storageClass: microk8s-hostpath
      size: 20Mi
    azure:
      storageClass: azurefile
      size: 5Gi

